### ISSUE TITLE
Template support

### ISSUE THREAD

**Issue by grimnight** [xplshn/Britto#1]
Please add template support.

It would make it possible to support languages other than english by simply adding few lines to config file.

**Comment by xplshn** [comment]
All UTF8 languages are supported. Are you talking about localizing the config itself?

**Comment by grimnight** [comment]
Maybe something like:
```toml
[templates]
due_today = "today"
due_tomorrow = "tomorrow"
due_in = "in %d days"
date_format_short = "02/01"
date_format = "02/01/2006"
Birthday0 = "[%s]'s birthday is %s! %s\n"
Birthday = "[%s] is turning %d years old %s! %s\n"
Reminder = "[%s] is due %s! %s - %s\n"
```
(The names of config entries is only meant as a placeholder)

Hopefully I didn't miss any template strings.
