### ISSUE TITLE
Incorrect due date

### ISSUE THREAD

**Issue by grimnight** [xplshn/Britto#3]
With config:
```toml
[template]
  due_today = "today"
  due_tomorrow = "tomorrow"
  due_in = "in {{.AgeOrDays}} days"
  date_format_short = "02/01"
  date_format = "02/01/2006"
  Birthday0 = "[{{.Name}}]'s birthday is {{.Due}}! {{.Date}}\n"
  Birthday = "[{{.Name}}] is turning {{.AgeOrDays}} years old {{.Due}}! {{.Date}}"
  Reminder = "[{{.Name}}] is due {{.Due}}! {{.Date}} - {{.Due}}"

[[Reminder]]
  Name = "Example Event"
  Date = "21/10/2024"
  Message = "Don't forget about the Example Event!"
```

I get output:
```shell
❯ date +%d/%m/%Y
20/10/2024

❯ britto
[Example Event] is due in 2 days! 21/10 - in 2 days
Don't forget about the Example Event!
```

Which should say `tomorrow`.
Also, should `Message` be part of template section?

PS. Sorry for spamming so many issues in such a short time.

**Comment by xplshn** [comment]
> Also, should Message be part of template section?
 
 I don't think so, Message is per-event, you can add Message to any event, birthday or reminder.

> Which should say tomorrow.

Will get to work on this, thanks for reporting

Britto is not something that I use a lot, its there on my terminal config just so I don't forget about birthday's, the rest are just niceties that I thought would be great. So sorry for so many inconveniences

**Comment by xplshn** [comment]
Fixed!

**Comment by grimnight** [comment]
Sorry if I was unclear.
I meant adding `Message` as a part of the template string, making it possible to have one line per event/birthday.

**Comment by grimnight** [comment]
Reminders seem to work correctly now.
Unfortunately birthdays aren't shown, at all.

**Comment by xplshn** [comment]
> Sorry if I was unclear. I meant adding `Message` as a part of the template string, making it possible to have one line per event/birthday.

I'm not sure I understand what you mean........................... Please show me an example.

**Comment by xplshn** [comment]
> Reminders seem to work correctly now. Unfortunately birthdays aren't shown, at all.

That's kind of odd, they do work on my PC, let me check if there are any logic errors in the code
EDIT: Dumb mistake spotted, I should get some sleep before pushing code to any of my repos :cry:

**Comment by grimnight** [comment]
I thought of something like:
```toml
[template]
  Birthday = "[{{.Name}}] is turning {{.AgeOrDays}} years old {{.Due}}! {{.Date}} - {{.Message}}"
  Reminder = "[{{.Name}}] is due {{.Due}}! {{.Date}} - {{.Due}} - {{.Message}}"
```
or:
```toml
[template]
  Birthday = "[{{.Name}}] is turning {{.AgeOrDays}} years old {{.Due}}! {{.Date}}\n{{.Message}}"
  Reminder = "[{{.Name}}] is due {{.Due}}! {{.Date}} - {{.Due}}\n{{.Message}}"
```

If that makes sense.

**Comment by grimnight** [comment]
After thinking on this some more, I think it might make more sense if it was like this:
```toml
[template]
  FormattedMessage = " - {{.Message}}"
  Birthday = "[{{.Name}}] is turning {{.AgeOrDays}} years old {{.Due}}! {{.Date}}{{.FormattedMessage}}"
  Reminder = "[{{.Name}}] is due {{.Due}}! {{.Date}} - {{.Due}}{{if .Message }}{{.FormattedMessage}}{{end}}"
```
or:
```toml
[template]
  FormattedMessage = "\n{{.Message}}"
  Birthday = "[{{.Name}}] is turning {{.AgeOrDays}} years old {{.Due}}! {{.Date}}{{.FormattedMessage}}"
  Reminder = "[{{.Name}}] is due {{.Due}}! {{.Date}} - {{.Due}}{{if .Message }}{{.FormattedMessage}}{{end}}"
```

Edit: Added `{{if .Message }}{{.FormattedMessage}}{{end}}`
